# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jeolad
# "service" is the name of this project. This will also be added to your AWS resource names.
service: stock-wise-api

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
